master:
  push:
    - docker:
        build: 
          dockerfile: ./helm/docker/Dockerfile
          by:
            - public
            - resources
            - package.json
            - package-lock.json
            - vite.config.js
            - composer.json
            - composer.lock
      stages:
        - name: sayhi
          script: echo "hi"