master:
  push:
    - docker:
        build: ./helm/docker/Dockerfile
        context: .
        by:
          - public
          - resources
          - package.json
          - package-lock.json
          - vite.config.js
          - composer.json
          - composer.lock
      stages:
        - name: sayhi
          script: echo "hi"